version: '3'

services:
    ms-sql-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        container_name: ms-sql-server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Pa55w0rd2020
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        restart: always
    user-service:
        build: .
        image: danialaswad/user-service
        container_name: user-service
        environment:
            - DBSERVER=ms-sql-server
            - DBPassword=Pa55w0rd2020
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Pa55w0rd2020
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/userservice.pfx
        ports:
            - "8080:80"
            - "8081:443"
        restart: always
        volumes:
            - ~/.aspnet/https:/https:ro
        depends_on:
            - ms-sql-server


