version: '3'

services:
    ms-sql-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        container_name: ms-sql-server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Pa55w0rd2020
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        restart: always
    user-service:
        build: .
        image: userappwebapi.azurecr.io/user-service
        container_name: user-service
        environment:
            - DBSERVER=ms-sql-server
            - DBPassword=Pa55w0rd2020
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "80:80"
        restart: always
        depends_on:
            - ms-sql-server


