apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels: 
        app: webapi
    spec:
      containers:
      - name: webapi
        image: danialaswad/user-service:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: user-service-configmap
              key: environment
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: user-service-configmap
              key: aspnetcore_url
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: user-service-xcert-password
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          valueFrom:
            configMapKeyRef:
              name: user-service-configmap
              key: aspnet_kernel_path
        - name: DBSERVER
          valueFrom:
            configMapKeyRef:
              name: user-service-configmap
              key: mssql-server
        - name: DBPassword
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: mssql-sa-password

---
apiVersion: v1
kind: Service
metadata: 
  name: user-service
spec: 
  selector:
    app: webapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      target: 8081
      nodeport: 30000